name: Go CI/CD

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: |
        cd rate-api-go
        go build -v -o rate-api .      

    - name: Create Release and Upload Asset
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs');
          const { owner, repo } = context.repo;
          const release = await github.rest.repos.createRelease({
            owner,
            repo,
            tag_name: process.env.GITHUB_REF,
            name: `Release ${process.env.GITHUB_REF}`,
            draft: false,
            prerelease: false
          });
          
          const asset = await github.rest.repos.uploadReleaseAsset({
            owner,
            repo,
            release_id: release.data.id,
            name: 'rate-api',
            data: fs.readFileSync('./rate-api-go/rate-api')
          });

